#!/bin/bash

create_html() {
	mkdir -p $3
	mkdir $3/templates
	exec 1> "$3/templates/$2".html
	cat<<-END
<!doctype html>
<html>
        <head>
                <title>$1</title>
        </head>
        <body>
                <h1>This is the $2 page.</h1>
        </body>
</html>
	END
	return
}

create_html_css() {
	mkdir -p $3
	mkdir $3/templates
	mkdir $3/static
	mkdir $3/static/styles
	exec 1> "$3/templates/$2".html
	cat<<-END
<!doctype html>
<html>
        <head>
                <title>$1</title>
                <link rel='stylesheet' href='{{ url_for("static", filename="$3/static/styles/$2.css") }}'>
        </head>
        <body>
                <h1>This is the $2 page.</h1>
        </body>
</html>
	END
	return
}

echo "What is the name of the webpage?"
read webpage_name

echo "What is the title of this webpage? "
read webpage_title

echo "Is there a CSS file? (If so, type yes)"
read css_response

echo "Where will you be putting these files (absolute path)?"
read location

if [[ "$css_response" == "yes" ]]; then
	create_html_css "$webpage_title" "$webpage_name" "$location" 
else
	create_html "$webpage_title" "$webpage_name" "$location"
fi	

