#!/bin/bash

INTEGER_CLASSIFICATION="The integer is $1"
INTEGER_SCALAR_FACTORIAL="Multiplying $1 by $2! gives us"
integer=$1
bound=$2

integer_classification () {
	if (( integer == 0 )); then
		echo "
		<p>Our integer is 0</p>
		"
	else
		if (( integer < 0 )); then
			echo "
			<p>Our integer is negative</p>
			"
		else
			echo "
			<p>Our integer is positive</p>
			"
		fi
	fi
}

integer_scalar_factorial () {


	count=1

	while [[ "$count" -le "$bound" ]]; do
		integer=$((integer*count))
		count=$((count + 1))
	done

	echo "$integer"
}

echo "
<html>
	<head>
		<title>Tutorials</title>
		<meta name='viewport' content='width=device-width'>
		<link rel='stylesheet' type='text/css' href='{{ url_for(\"static\", filename=\"styles/integer_input.css\") }}'>
	</head>
	<body>
		<div id='opening'>
			<div id='nav'>
				<ul>
					<li><a href='{{ url_for(\"main.index\") }}'>Home</a></li>
				</ul>
			</div>
		</div>
		<div id='content'>
			<div id='integer'>
				<p>Integer Classification</p>
				<p>$INTEGER_CLASSIFICATION</p>
				<p>$(integer_classification)</p>
				<p>$INTEGER_SCALAR_FACTORIAL</p>
				<p>$(integer_scalar_factorial)</p>
			</div>
	</body>
</html>
"


