#!/bin/bash

RESULT="The integer is $1"
INT=$1

result_for_integer () {
	if (( INT == 0 )); then
		echo "
		<p>Our integer is 0</p>
		"
	else
		if (( INT < 0 )); then
			echo "
			<p>Our integer is negative</p>
			"
		else
			echo "
			<p>Our integer is positive</p>
			"
		fi
	fi
}

echo "
<html>
	<head>
		<title>Tutorials</title>
		<meta name='viewport' content='width=device-width'>
		<link rel='stylesheet' type='text/css' href='{{ url_for(\"static\", filename=\"styles/integer_input.css\") }}'>
	</head>
	<body>
		<div id='opening'>
			<div id='nav'>
				<ul>
					<li><a href='{{ url_for(\"main.index\") }}'>Home</a></li>
				</ul>
			</div>
		</div>
		<div id='content'>
			<div id='integer'>
				<p>Integer Classification</p>
				<h1>$RESULT</h1>
				$(result_for_integer)
			</div>
	</body>
</html>
"


