#!/bin/bash


report_uptime () {
	echo "
	<h2 class="Message">System Uptime</h2>
	<pre class="Message">$(uptime)</pre>
	"
	return
}

echo "
<html>
	<head>
		<title>Tutorials</title>
		<meta name='viewport' content='width=device-width'>
		<link rel='stylesheet' type='text/css' href='{{ url_for(\"static\", filename=\"styles/uptime.css\") }}'>
	</head>
	<body>
		<div id='opening'>
			<div id='nav'>
				<ul>
					<li><a href='{{ url_for(\"main.index\") }}'>Home</a></li>
				</ul>
			</div>
		</div>
		<div id='content'>
			<div id='uptime'>
				<h1>Uptime Report</h1>
				$(report_uptime)
			</div>
	</body>
</html>
"
